#!/bin/bash
scriptdir="`dirname \"$0\"`"
cd $scriptdir/../ \
	&& git pull \
	&& source deploy/pyenv/bin/activate \
	&& pip install -U pip \
	&& pip install -U -r support/requirements.txt \
	&& ( cd trackersite \
		&& python manage.py syncdb \
		&& python manage.py migrate \
		&& python manage.py collectstatic --noinput \
		&& python manage.py compilemessages \
	) \
	&& touch deploy/reload
